# Generated by Django 4.2.1 on 2023-06-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('O', 'OPEN'), ('W', 'WORKING'), ('D', 'DONE'), ('OD', 'OVERDUE')], default='O', max_length=2),
        ),
    ]
